import type { AgentDefinition, AgentPromptContext } from '@/types/agent.types';

// ─── Shared system prompt prefix ────────────────────────────────────────────
const BASE_SYSTEM = `You are a senior software engineering consultant producing professional SDLC documentation.
Your output must be comprehensive, well-structured, and directly actionable by a development team.
Use Markdown formatting with clear headings and sections.
Be specific — avoid generic filler content. Reference the project's domain context in every document.
Output only the document itself — no preamble, no meta-commentary.`;

// ─── Helpers ─────────────────────────────────────────────────────────────────
function domainLine(ctx: AgentPromptContext): string {
  return `\n\n## Domain Context\n${ctx.domainContext}`;
}

function teamLine(ctx: AgentPromptContext): string {
  if (!ctx.teamRoster || ctx.teamRoster.length === 0) return '';
  const rows = ctx.teamRoster.map((m) => `- **${m.name}** — ${m.role}`).join('\n');
  return `\n\n## Project Team\nUse these real names and roles when documents require team members, owners, approvers, or assignees:\n${rows}`;
}


function diagramLine(hint: string): string {
  return `\n\n## Diagram Requirement\nYou MUST include at least one Mermaid diagram in your output. Use a fenced code block with the language tag \`\`\`mermaid. ${hint} Use valid Mermaid syntax (flowchart TD, sequenceDiagram, erDiagram, classDiagram, or C4Context as appropriate).`;
}

function brandingLine(ctx: AgentPromptContext): string {
  if (ctx.brandingGuidelines && ctx.brandingGuidelines.trim()) {
    return `\n\n## Branding Guidelines (owner-supplied)\n${ctx.brandingGuidelines}\nFollow these guidelines for both design concept versions below.`;
  }
  return `\n\n## Branding Guidelines\nNo branding guidelines were supplied by the project owner. Default to visual conventions and design patterns standard for the ${ctx.domain} domain/industry.`;
}

// ─── Phase 1 ─────────────────────────────────────────────────────────────────
const manager: AgentDefinition = {
  id: 'manager',
  name: 'SDLC Orchestrator',
  phase: 'phase1',
  description: 'Generates the Product Requirements Document (PRD)',
  outputLabel: 'Product Requirements Document',
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the SDLC Orchestrator Agent. Your task is to produce a complete Product Requirements Document (PRD).`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `Description: ${ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce a complete PRD with the following sections:`,
    `1. Executive Summary`,
    `2. Problem Statement & Opportunity`,
    `3. Goals & Success Metrics (KPIs)`,
    `4. Scope (In-scope / Out-of-scope)`,
    `5. User Personas (3-5 personas with goals and pain points)`,
    `6. Functional Requirements (numbered, MoSCoW priority)`,
    `7. Non-Functional Requirements (performance, security, scalability, accessibility)`,
    `8. Assumptions & Constraints`,
    `9. Dependencies`,
    `10. Timeline & Milestones (high level)`,
    `11. Risks & Mitigations`,
  ].join('\n'),
};

// ─── Phase 1B ────────────────────────────────────────────────────────────────
const projectCharter: AgentDefinition = {
  id: 'projectCharter',
  name: 'Project Charter',
  phase: 'phase1b',
  description: 'Generates the Project Charter',
  outputLabel: 'Project Charter',
  dependsOn: ['manager'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the Project Charter Agent. Your task is to produce a formal Project Charter document.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `PRD Summary:\n${ctx.priorOutputs.manager?.slice(0, 2000) ?? 'See project description below.'}`,
    `Project Description: ${ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce a Project Charter with:`,
    `1. Project Title & Version`,
    `2. Project Purpose & Justification`,
    `3. Project Objectives (SMART)`,
    `4. High-Level Scope`,
    `5. Project Sponsor & Stakeholders`,
    `6. Project Manager & Team Roles (use the actual team member names provided above)`,
    `7. Budget Estimate (rough order of magnitude)`,
    `8. Schedule Summary`,
    `9. Success Criteria`,
    `10. Approval Signatures section (list actual team members by name and role)`,
  ].join('\n'),
};

const brd: AgentDefinition = {
  id: 'brd',
  name: 'Business Requirements',
  phase: 'phase1b',
  description: 'Generates the Business Requirements Document (BRD)',
  outputLabel: 'Business Requirements Document',
  dependsOn: ['manager'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the Business Requirements Agent. Your task is to produce a comprehensive Business Requirements Document (BRD).`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `PRD Summary:\n${ctx.priorOutputs.manager?.slice(0, 2000) ?? 'See project description below.'}`,
    `Project Description: ${ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce a BRD with:`,
    `1. Business Context & Background`,
    `2. Business Objectives`,
    `3. Current State vs Future State`,
    `4. Business Process Flows (describe in text/pseudo-diagram)`,
    `5. Stakeholder Analysis (RACI matrix — use actual team member names as owners)`,
    `6. Business Requirements (numbered BR-001, BR-002, ...)`,
    `7. Business Rules`,
    `8. Compliance & Regulatory Requirements`,
    `9. Reporting & Analytics Requirements`,
    `10. Change Management Considerations`,
  ].join('\n'),
};

// ─── Phase 2 ──────────────────────────────────────────────────────────────────
const stakeholder: AgentDefinition = {
  id: 'stakeholder',
  name: 'Stakeholder Analysis',
  phase: 'phase2',
  description: 'Comprehensive stakeholder register and engagement plan',
  outputLabel: 'Stakeholder Analysis',
  dependsOn: ['projectCharter', 'brd'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the Stakeholder Analysis Agent.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `Description: ${ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce a Stakeholder Analysis document with:`,
    `1. Stakeholder Register (table: Name/Role, Interest, Influence, Impact, Engagement Strategy) — include all actual team members listed above`,
    `2. Power/Interest Grid description (4 quadrants: Manage Closely, Keep Satisfied, Keep Informed, Monitor)`,
    `3. Communication Plan (stakeholder, frequency, channel, message type) — assign team member names to communication owners`,
    `4. Resistance & Change Management`,
    `5. Stakeholder-to-Requirement Traceability`,
  ].join('\n'),
};

const userStory: AgentDefinition = {
  id: 'userStory',
  name: 'User Stories',
  phase: 'phase2',
  description: 'Epic and user story backlog with acceptance criteria',
  outputLabel: 'User Stories & Backlog',
  dependsOn: ['manager'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the User Story Agent. Produce detailed epics and user stories in standard agile format.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `PRD Excerpt:\n${ctx.priorOutputs.manager?.slice(0, 1500) ?? ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce a User Story Backlog with:`,
    `1. At least 5 Epics with descriptions`,
    `2. For each Epic, 3-5 User Stories in format: "As a [persona], I want [capability] so that [benefit]"`,
    `3. Each story must have: Story Points estimate, Priority (P0/P1/P2), Acceptance Criteria (3+ criteria in Given/When/Then format), and Owner (assign from the actual team member names above)`,
    `4. Definition of Done`,
    `5. Non-functional stories (performance, security, accessibility)`,
  ].join('\n'),
};

const businessRules: AgentDefinition = {
  id: 'businessRules',
  name: 'Business Rules',
  phase: 'phase2',
  description: 'Business rules engine and validation logic',
  outputLabel: 'Business Rules Document',
  dependsOn: ['brd'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the Business Rules Agent.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `BRD Excerpt:\n${ctx.priorOutputs.brd?.slice(0, 1500) ?? ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce a Business Rules Document with:`,
    `1. Rule Categories (validation, calculation, workflow, compliance)`,
    `2. Business Rules Register (table: Rule ID, Name, Description, Trigger, Action, Priority, Source, Owner) — assign owners from actual team member names above`,
    `3. Decision Tables for complex conditional logic`,
    `4. Workflow Rules (state transitions, approvals)`,
    `5. Domain-Specific Compliance Rules`,
    `6. Rule Conflict Analysis`,
    `7. Implementation Notes per rule category`,
  ].join('\n'),
};

const feasibility: AgentDefinition = {
  id: 'feasibility',
  name: 'Feasibility Study',
  phase: 'phase2',
  description: 'Technical, operational and financial feasibility analysis',
  outputLabel: 'Feasibility Study',
  dependsOn: ['manager', 'brd'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the Feasibility Study Agent.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `Description: ${ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce a Feasibility Study with:`,
    `1. Executive Summary`,
    `2. Technical Feasibility (technology stack assessment, integration complexity, team skills gap)`,
    `3. Operational Feasibility (process changes, training needs, support model)`,
    `4. Financial Feasibility (cost-benefit analysis, ROI estimate, TCO, NPV if possible)`,
    `5. Schedule Feasibility (timeline risk, critical path)`,
    `6. Risk Assessment (top 10 risks, likelihood x impact matrix)`,
    `7. Alternative Solutions Considered`,
    `8. Recommendation & Go/No-Go decision framework — attribute sign-off to named team members above`,
  ].join('\n'),
};

const dataModel: AgentDefinition = {
  id: 'dataModel',
  name: 'Data Model',
  phase: 'phase2',
  description: 'Entity relationship model and data dictionary',
  outputLabel: 'Data Model & Dictionary',
  dependsOn: ['businessRules'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the Data Modeling Agent.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `Description: ${ctx.projectDescription}`,
    `Business Rules Excerpt:\n${ctx.priorOutputs.businessRules?.slice(0, 1000) ?? ''}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce a Data Model document with:`,
    `1. Conceptual Data Model (describe entities and relationships in text)`,
    `2. Logical Data Model — Entity-Relationship description with:`,
    `   - All entities (table name, description)`,
    `   - Attributes (field name, data type, constraints, description)`,
    `   - Relationships (cardinality: 1:1, 1:N, M:N)`,
    `3. Data Dictionary (table: Entity, Field, Type, Nullable, Default, Description, Validation, Owner — use actual team member names as data owners)`,
    `4. Data Flow Description`,
    `5. Data Retention & Archival Policy`,
    `6. PII / Sensitive Data Classification`,
    `7. Indexing Strategy`,
    diagramLine('Draw an erDiagram showing all entities and their relationships with cardinality.'),
  ].join('\n'),
};

// ─── Phase 3 ──────────────────────────────────────────────────────────────────
const architecture: AgentDefinition = {
  id: 'architecture',
  name: 'Architecture',
  phase: 'phase3',
  description: 'System architecture, tech stack and infrastructure design',
  outputLabel: 'Architecture Design Document',
  dependsOn: ['dataModel', 'feasibility'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the Software Architect Agent.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `Description: ${ctx.projectDescription}`,
    `Data Model Summary:\n${ctx.priorOutputs.dataModel?.slice(0, 1000) ?? ''}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce an Architecture Design Document (ADD) with:`,
    `1. Architecture Overview & Guiding Principles`,
    `2. System Context Diagram (described in text/ASCII)`,
    `3. Component Diagram (services, their responsibilities, interfaces)`,
    `4. Technology Stack Decision (frontend, backend, database, cache, messaging, infra) with justification`,
    `5. Integration Architecture (external APIs, event bus, webhooks)`,
    `6. Data Architecture (storage layers, caching strategy, CDN)`,
    `7. Security Architecture (AuthN/AuthZ, secrets management, network segmentation)`,
    `8. Scalability & Performance Design`,
    `9. Disaster Recovery & High Availability strategy`,
    `10. Architecture Decision Records (ADRs) — at least 3 key decisions, each attributed to the responsible architect or tech lead by name from the team above`,
    diagramLine('Draw a high-level C4 Context or component diagram showing services and their interactions.'),
  ].join('\n'),
};

const apiDesign: AgentDefinition = {
  id: 'apiDesign',
  name: 'API Design',
  phase: 'phase3',
  description: 'RESTful API specification and contract design',
  outputLabel: 'API Design Specification',
  dependsOn: ['architecture'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the API Design Agent. Produce a comprehensive REST API specification.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `Architecture Summary:\n${ctx.priorOutputs.architecture?.slice(0, 1200) ?? ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce an API Design Specification with:`,
    `1. API Design Principles (REST, versioning strategy, naming conventions)`,
    `2. Authentication & Authorization (JWT, OAuth2, API keys)`,
    `3. Base URL & Versioning`,
    `4. Core Endpoints — for each endpoint:`,
    `   - Method + Path`,
    `   - Description`,
    `   - Request headers, path params, query params, body (with types)`,
    `   - Response schema (200, 400, 401, 404, 500)`,
    `   - Example request/response`,
    `   - Owner (assign from team member names above)`,
    `5. Pagination, Filtering, Sorting patterns`,
    `6. Error Response Format`,
    `7. Rate Limiting Headers`,
    `8. Webhook Events (if applicable)`,
    `9. API Changelog section template`,
    diagramLine('Draw a sequenceDiagram showing the auth flow and at least one core API request-response cycle.'),
  ].join('\n'),
};

const uxResearch: AgentDefinition = {
  id: 'uxResearch',
  name: 'UX Research',
  phase: 'phase3',
  description: 'UX research findings, journey maps, and design principles',
  outputLabel: 'UX Research Report',
  dependsOn: ['userStory', 'stakeholder'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the UX Research Agent.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `User Stories Excerpt:\n${ctx.priorOutputs.userStory?.slice(0, 1200) ?? ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce a UX Research Report with:`,
    `1. Research Objectives & Methodology (assign research lead from team member names above)`,
    `2. User Persona Deep Dives (3 personas: goals, pain points, tech comfort, context of use)`,
    `3. User Journey Maps (2 key journeys: current state vs future state)`,
    `4. Usability Heuristics Analysis`,
    `5. Accessibility Requirements (WCAG 2.1 AA checklist items relevant to this domain)`,
    `6. Competitive UX Analysis (3 comparable products, what they do well/poorly)`,
    `7. Design Principles for this product`,
    `8. Information Architecture (site map / navigation structure)`,
  ].join('\n'),
};

const interaction: AgentDefinition = {
  id: 'interaction',
  name: 'Interaction Design',
  phase: 'phase3',
  description: 'Wireframe descriptions, component library and interaction patterns',
  outputLabel: 'Interaction Design Spec',
  dependsOn: ['uxResearch'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the Interaction Design Agent.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `UX Research Excerpt:\n${ctx.priorOutputs.uxResearch?.slice(0, 1200) ?? ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce an Interaction Design Specification with:`,
    `1. Design System Overview (color palette, typography, spacing, iconography)`,
    `2. Component Library (buttons, forms, cards, modals, tables, navigation — describe each)`,
    `3. Key Screen Wireframes (text descriptions of layout for 5+ screens)`,
    `4. Interaction Patterns (hover states, loading states, error states, empty states)`,
    `5. Responsive Design Breakpoints`,
    `6. Micro-interactions & Animations guidelines`,
    `7. Form Design Patterns (validation, error messages, inline help)`,
    `8. Accessibility Implementation Notes`,
  ].join('\n'),
};

const uxMockups: AgentDefinition = {
  id: 'uxMockups',
  name: 'UX Mockups',
  phase: 'phase3',
  description: 'Two UX design concept versions (wireframes + diagrams) based on UX research, interaction design, and branding guidelines',
  outputLabel: 'UX Mockups & Style Guide',
  dependsOn: ['uxResearch', 'interaction', 'architecture'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the UX Mockups Agent. You translate UX research and interaction design into concrete visual design concepts. Since you cannot generate raster images directly, you express each mockup as a detailed wireframe description PLUS a Mermaid diagram (using flowchart/graph syntax with subgraphs to represent screen regions, components, and layout) so the layout can be rendered as an image.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `UX Research Excerpt:\n${ctx.priorOutputs.uxResearch?.slice(0, 1200) ?? ctx.projectDescription}`,
    `Interaction Design Excerpt:\n${ctx.priorOutputs.interaction?.slice(0, 1200) ?? ''}`,
    `Architecture Summary (for platform/tech constraints):\n${ctx.priorOutputs.architecture?.slice(0, 600) ?? ''}`,
    domainLine(ctx),
    teamLine(ctx),
    brandingLine(ctx),
    `\nProduce a UX Mockups & Style Guide document with TWO distinct design concept versions, each appropriate for the ${ctx.domain} domain and following industry-standard UX patterns for that domain. Structure the output as:`,
    `1. Style Guide (shared by both versions): color palette (with hex codes), typography scale, spacing/grid system, iconography style, button/input states — informed by the branding guidelines above`,
    `2. Version A — Concept Name & Rationale (1-2 sentences on the design direction and why it fits this domain/audience)`,
    `3. Version A — Wireframe Mockups: for the 3 most important screens identified in the UX research/interaction design, provide:`,
    `   - A short layout description (header, nav, content regions, key components, CTAs)`,
    `   - A Mermaid diagram (flowchart TD with subgraphs representing the screen's regions/components, e.g. subgraph "Header", subgraph "Main Content") in a fenced \`\`\`mermaid code block — one diagram per screen`,
    `4. Version B — Concept Name & Rationale (a meaningfully different visual/layout direction from Version A — e.g. different information density, navigation pattern, or visual style — while still fitting the domain)`,
    `5. Version B — Wireframe Mockups: same 3 screens as Version A, each with a layout description and its own \`\`\`mermaid flowchart diagram showing the alternative layout`,
    `6. Comparison & Recommendation: a short table comparing Version A vs Version B (strengths, trade-offs) and a recommendation for which to prototype first, with rationale`,
    `\nIMPORTANT: You must produce at least 6 \`\`\`mermaid fenced code blocks total (3 screens x 2 versions), each using flowchart/graph syntax with subgraphs to represent the wireframe layout. Do not use C4Context or sequenceDiagram for the wireframes — use flowchart TD with subgraphs only.`,
  ].join('\n'),
};

// ─── Phase 4 ──────────────────────────────────────────────────────────────────
const sprintPlanner: AgentDefinition = {
  id: 'sprintPlanner',
  name: 'Sprint Planner',
  phase: 'phase4',
  description: 'Sprint plan with capacity and velocity estimation',
  outputLabel: 'Sprint Plan',
  dependsOn: ['userStory', 'architecture'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the Sprint Planning Agent.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `User Stories Excerpt:\n${ctx.priorOutputs.userStory?.slice(0, 1500) ?? ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce a Sprint Plan with:`,
    `1. Release Strategy (MVP vs. subsequent releases)`,
    `2. Sprint 0 — Setup & Infrastructure tasks (assign owners from actual team member names above)`,
    `3. Sprints 1-6 (2-week sprints):`,
    `   - Sprint Goal`,
    `   - Stories included (reference story IDs)`,
    `   - Estimated story points`,
    `   - Team capacity assumptions (reference actual team members and their roles)`,
    `4. Velocity Assumptions & Burn-down approach`,
    `5. Definition of Ready / Definition of Done`,
    `6. Dependencies between sprints`,
    `7. Release milestones`,
  ].join('\n'),
};

const taskBreakdown: AgentDefinition = {
  id: 'taskBreakdown',
  name: 'Task Breakdown',
  phase: 'phase4',
  description: 'Granular engineering task breakdown for Phase 1 implementation',
  outputLabel: 'Engineering Task Breakdown',
  dependsOn: ['architecture', 'apiDesign'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the Task Breakdown Agent. Break high-level stories into concrete engineering tasks.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `Architecture Summary:\n${ctx.priorOutputs.architecture?.slice(0, 1000) ?? ''}`,
    `API Design Summary:\n${ctx.priorOutputs.apiDesign?.slice(0, 1000) ?? ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce an Engineering Task Breakdown with:`,
    `1. Backend Tasks (group by service/module)`,
    `2. Frontend Tasks (group by feature/page)`,
    `3. Infrastructure / DevOps Tasks`,
    `4. Testing Tasks`,
    `5. For each task: Task ID, Title, Description, Estimated Hours, Assignee (use actual team member names matched to their role), Dependencies, Acceptance Criteria`,
    `6. Critical Path Analysis`,
    `7. Technical Spikes required (unknowns to investigate)`,
  ].join('\n'),
};

const techDebt: AgentDefinition = {
  id: 'techDebt',
  name: 'Tech Debt Register',
  phase: 'phase4',
  description: 'Known tech debt, shortcuts and future refactoring plan',
  outputLabel: 'Tech Debt Register',
  dependsOn: ['architecture'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the Technical Debt Management Agent.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `Architecture Summary:\n${ctx.priorOutputs.architecture?.slice(0, 1200) ?? ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce a Tech Debt Register with:`,
    `1. Planned Technical Shortcuts (accepted for MVP — describe each with rationale)`,
    `2. Tech Debt Register (table: ID, Category, Description, Impact, Effort to Fix, Priority, Target Sprint, Owner — assign owners from actual team member names above)`,
    `3. Architectural Debt items`,
    `4. Dependency & Upgrade Schedule`,
    `5. Code Quality Targets (coverage %, linting rules, complexity thresholds)`,
    `6. Refactoring Roadmap (post-MVP phases)`,
    `7. Monitoring for Debt Growth`,
  ].join('\n'),
};

const codeStructure: AgentDefinition = {
  id: 'codeStructure',
  name: 'Code Structure Generator',
  phase: 'phase4',
  description: 'Recommended repository and code folder structure based on the architecture',
  outputLabel: 'Code Folder Structure',
  dependsOn: ['architecture'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the Code Structure Agent. Translate the system architecture into a concrete, opinionated repository and folder layout that engineers can scaffold immediately.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `Architecture Summary:\n${ctx.priorOutputs.architecture?.slice(0, 1800) ?? ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce a Code Folder Structure document with:`,
    `1. Repository Strategy (monorepo vs. polyrepo, with rationale tied to the architecture above)`,
    `2. Top-level Directory Tree — show the FULL tree inside a single fenced code block using the \`text\` language tag (e.g. \`\`\`text), using standard tree characters (├──, └──, │)`,
    `3. Purpose of each top-level directory and key subdirectory (short bullet per folder)`,
    `4. Module/Service Boundaries — how the tree maps to the services/components named in the architecture`,
    `5. Naming Conventions (files, folders, modules, components)`,
    `6. Configuration & Environment File Placement (.env, config/, infra-as-code, CI/CD)`,
    `7. Where Tests Live (mirroring strategy vs. co-location)`,
    `8. Notes for Scaffolding Tooling (e.g. what a generator/CLI should create first)`,
  ].join('\n'),
};

const codeSnippets: AgentDefinition = {
  id: 'codeSnippets',
  name: 'Code Snippet Generator',
  phase: 'phase4',
  description: 'Representative starter code snippets derived from the architecture, API design, and UX/interaction design',
  outputLabel: 'Code Snippets',
  dependsOn: ['architecture', 'apiDesign', 'interaction'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the Code Snippet Agent. Produce representative, runnable-quality starter code that gives engineers a concrete head start, grounded in the architecture, API design, and UX/interaction design provided.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `Architecture Summary:\n${ctx.priorOutputs.architecture?.slice(0, 1200) ?? ''}`,
    `API Design Summary:\n${ctx.priorOutputs.apiDesign?.slice(0, 1200) ?? ''}`,
    `Interaction/UX Design Summary:\n${ctx.priorOutputs.interaction?.slice(0, 1000) ?? ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce a Code Snippets document with:`,
    `1. Brief intro naming the languages/frameworks assumed (consistent with the architecture above)`,
    `2. One representative Backend API Handler/Controller — for one key endpoint from the API Design, in a fenced code block with the correct language tag (e.g. \`\`\`typescript, \`\`\`python, \`\`\`java)`,
    `3. One representative Data Model / Entity definition matching the architecture's data layer, in a fenced code block with the correct language tag`,
    `4. One representative Frontend Component/Screen skeleton implementing a key interaction from the UX/Interaction design, in a fenced code block with the correct language tag (e.g. \`\`\`tsx, \`\`\`jsx, \`\`\`vue)`,
    `5. One representative Service/Business Logic function tying the above together, in a fenced code block`,
    `6. For each snippet: a short paragraph (before the code block) explaining what it does and where it fits in the folder structure`,
    `7. Keep each snippet concise (roughly 20-50 lines) and focused — favor clarity over completeness`,
  ].join('\n'),
};

const uiComponentLibrary: AgentDefinition = {
  id: 'uiComponentLibrary',
  name: 'UI Component Library',
  phase: 'phase4',
  description: 'Reusable UI component inventory and component library management strategy based on the interaction design and code structure',
  outputLabel: 'UI Component Library Plan',
  dependsOn: ['interaction', 'codeStructure'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the UI Component Library Agent. You identify the reusable UI components implied by the interaction design, decide which belong in a shared component library vs. which are page-specific, and define how the shared library should be structured, versioned, and maintained — following standard practices for component-driven frontend development (e.g. atomic design, design tokens, Storybook-style documentation).`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `Interaction Design Excerpt:\n${ctx.priorOutputs.interaction?.slice(0, 1500) ?? ctx.projectDescription}`,
    `Code Folder Structure Excerpt:\n${ctx.priorOutputs.codeStructure?.slice(0, 1000) ?? ''}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce a UI Component Library Plan with:`,
    `1. Component Inventory (table: Component Name, Category — atom/molecule/organism, Description, Used On Screens, Reusable? Yes/No)`,
    `2. Reusable Component Library — components that should live in a shared library: for each, note its props/variants (e.g. size, state, theme) and which design system primitives it depends on (colors, typography, spacing tokens)`,
    `3. Page-Specific Components — components that should NOT be generalized, with rationale`,
    `4. Component Library Folder Structure — where the shared library lives relative to the repo structure above (e.g. packages/ui, src/components/shared), in a fenced \`\`\`text code block showing the tree`,
    `5. Naming & Versioning Conventions for shared components (e.g. semantic versioning if published as an internal package, naming prefixes)`,
    `6. Documentation & Discovery Strategy (e.g. Storybook, a component catalog page) so engineers can find and reuse existing components before building new ones`,
    `7. Governance — who owns/reviews additions to the shared library (assign from actual team member names above), and the process for promoting a page-specific component into the shared library`,
    `8. Design Token Mapping — how the style guide's colors/typography/spacing map to reusable tokens consumed by these components`,
  ].join('\n'),
};

// ─── Phase 5 ──────────────────────────────────────────────────────────────────
const testPlan: AgentDefinition = {
  id: 'testPlan',
  name: 'Test Plan',
  phase: 'phase5',
  description: 'Master test plan covering all testing levels',
  outputLabel: 'Master Test Plan',
  dependsOn: ['architecture', 'userStory'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the Test Planning Agent.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `Architecture Summary:\n${ctx.priorOutputs.architecture?.slice(0, 1000) ?? ''}`,
    `User Stories Excerpt:\n${ctx.priorOutputs.userStory?.slice(0, 800) ?? ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce a Master Test Plan with:`,
    `1. Test Strategy Overview (assign test lead from actual team member names above)`,
    `2. Testing Levels: Unit, Integration, System, UAT, Performance, Security, Accessibility`,
    `3. Test Environment Requirements`,
    `4. Test Data Management`,
    `5. Test Tools & Frameworks`,
    `6. Entry/Exit Criteria per testing level`,
    `7. Defect Management Process (assign triage owners from team member names)`,
    `8. Test Metrics & Reporting`,
    `9. Risk-Based Testing Approach`,
    `10. Automation Strategy`,
  ].join('\n'),
};

const testCases: AgentDefinition = {
  id: 'testCases',
  name: 'Test Cases',
  phase: 'phase5',
  description: 'Detailed test cases for critical user flows',
  outputLabel: 'Test Cases',
  dependsOn: ['testPlan', 'userStory'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the Test Case Author Agent. Write detailed, executable test cases.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `Test Plan Summary:\n${ctx.priorOutputs.testPlan?.slice(0, 1000) ?? ''}`,
    `User Stories:\n${ctx.priorOutputs.userStory?.slice(0, 1000) ?? ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce Test Cases including:`,
    `1. Test Case Register (table: TC-ID, Title, Preconditions, Steps, Expected Result, Priority, Type, Author — use actual team member names as authors)`,
    `2. Happy Path test cases for 5 core flows`,
    `3. Negative test cases (invalid inputs, edge cases, error conditions)`,
    `4. Integration test cases (API contracts, database, third-party services)`,
    `5. Performance test scenarios (load, stress, spike)`,
    `6. Security test cases (OWASP Top 10 relevant items)`,
    `7. Accessibility test cases`,
    `8. Regression test suite outline`,
  ].join('\n'),
};

// ─── Phase 6 ──────────────────────────────────────────────────────────────────
const securityCompliance: AgentDefinition = {
  id: 'securityCompliance',
  name: 'Security & Compliance',
  phase: 'phase6',
  description: 'Security assessment, threat model and compliance checklist',
  outputLabel: 'Security & Compliance Report',
  dependsOn: ['architecture', 'dataModel'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the Security & Compliance Agent.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `Architecture Summary:\n${ctx.priorOutputs.architecture?.slice(0, 1000) ?? ''}`,
    `Data Model Summary:\n${ctx.priorOutputs.dataModel?.slice(0, 800) ?? ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce a Security & Compliance Report with:`,
    `1. Threat Model (STRIDE methodology — Spoofing, Tampering, Repudiation, Info Disclosure, DoS, Elevation)`,
    `2. Attack Surface Analysis`,
    `3. OWASP Top 10 Assessment (rate each item: High/Medium/Low risk, mitigations)`,
    `4. Authentication & Authorization Design`,
    `5. Data Protection Controls (encryption, masking, tokenization)`,
    `6. Network Security Controls`,
    `7. Compliance Checklist (domain-specific regulations)`,
    `8. Security Testing Requirements`,
    `9. Incident Response Plan outline — assign named roles to incident commander and escalation contacts from team members above`,
    `10. Security Runbook`,
  ].join('\n'),
};

// ─── Phase 7 ──────────────────────────────────────────────────────────────────
const devopsEngineer: AgentDefinition = {
  id: 'devopsEngineer',
  name: 'DevOps Engineer',
  phase: 'phase7',
  description: 'CI/CD pipeline design and deployment strategy',
  outputLabel: 'DevOps & CI/CD Design',
  dependsOn: ['architecture'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the DevOps Engineer Agent.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `Architecture Summary:\n${ctx.priorOutputs.architecture?.slice(0, 1200) ?? ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce a DevOps & CI/CD Design document with:`,
    `1. CI/CD Pipeline Architecture (stages: build, test, security scan, deploy)`,
    `2. Branch Strategy (GitFlow or trunk-based)`,
    `3. Environment Strategy (dev, staging, prod — promotion criteria)`,
    `4. Container Strategy (Dockerfile guidelines, image registry, tagging)`,
    `5. Deployment Strategy (blue/green, canary, rolling — with rationale)`,
    `6. Infrastructure as Code approach (Terraform / Pulumi)`,
    `7. Secret Management`,
    `8. Rollback Procedures`,
    `9. Pipeline YAML skeleton (GitHub Actions or equivalent)`,
    `10. DORA Metrics targets — assign metric owners from actual team member names above`,
    diagramLine('Draw a flowchart TD of the full CI/CD pipeline from code commit to production deployment.'),
  ].join('\n'),
};

const infraEngineer: AgentDefinition = {
  id: 'infraEngineer',
  name: 'Infrastructure Engineer',
  phase: 'phase7',
  description: 'Cloud infrastructure design and resource sizing',
  outputLabel: 'Infrastructure Design',
  dependsOn: ['architecture'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the Infrastructure Engineer Agent.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `Architecture Summary:\n${ctx.priorOutputs.architecture?.slice(0, 1200) ?? ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce an Infrastructure Design document with:`,
    `1. Cloud Provider Recommendation & Justification`,
    `2. Network Architecture (VPC, subnets, security groups, load balancers)`,
    `3. Compute Resources (instance types, auto-scaling groups, sizing rationale)`,
    `4. Database Infrastructure (managed services, read replicas, multi-AZ)`,
    `5. Storage Strategy (object storage, block storage, file storage)`,
    `6. CDN & Edge Configuration`,
    `7. Cost Estimate (monthly, by service)`,
    `8. Capacity Planning (6-month, 12-month projections)`,
    `9. Disaster Recovery Architecture (RPO/RTO targets)`,
    `10. Infrastructure Runbook — assign runbook owners from actual team member names above`,
    diagramLine('Draw a flowchart LR showing the cloud infrastructure topology (VPC, subnets, compute, load balancer, database, CDN).'),
  ].join('\n'),
};

// ─── Phase 8 ──────────────────────────────────────────────────────────────────
const observabilityEngineer: AgentDefinition = {
  id: 'observabilityEngineer',
  name: 'Observability Engineer',
  phase: 'phase8',
  description: 'Monitoring, logging, tracing and alerting design',
  outputLabel: 'Observability Design',
  dependsOn: ['devopsEngineer', 'infraEngineer'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the Observability Engineer Agent.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `Architecture Summary:\n${ctx.priorOutputs.architecture?.slice(0, 800) ?? ''}`,
    `Infrastructure Summary:\n${ctx.priorOutputs.infraEngineer?.slice(0, 800) ?? ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce an Observability Design document with:`,
    `1. Observability Strategy (pillars: Metrics, Logs, Traces) — assign observability lead from actual team member names above`,
    `2. Metrics Design (SLIs, SLOs, SLAs — define at least 5 SLIs)`,
    `3. Logging Strategy (log levels, structured logging schema, retention)`,
    `4. Distributed Tracing Design`,
    `5. Dashboard Design (list of dashboards and key panels)`,
    `6. Alerting Rules (table: Alert Name, Condition, Severity, On-Call Action, Owner — use actual team member names as owners)`,
    `7. Synthetic Monitoring`,
    `8. Tooling Stack (Prometheus, Grafana, OpenTelemetry, etc.)`,
    `9. Runbook Template`,
    diagramLine('Draw a sequenceDiagram showing the alerting pipeline: metric threshold → alert → on-call notification → escalation → resolution.'),
  ].join('\n'),
};

const onCallEngineer: AgentDefinition = {
  id: 'onCallEngineer',
  name: 'On-Call Engineer',
  phase: 'phase8',
  description: 'On-call playbook, incident runbooks and escalation procedures',
  outputLabel: 'On-Call Playbook',
  dependsOn: ['observabilityEngineer', 'securityCompliance'],
  systemPrompt: `${BASE_SYSTEM}\n\nYou are the On-Call Engineering Agent. Your output is the definitive operational playbook.`,
  buildUserPrompt: (ctx) => [
    `Project: ${ctx.projectName}`,
    `Observability Design:\n${ctx.priorOutputs.observabilityEngineer?.slice(0, 1000) ?? ''}`,
    `Security Report Summary:\n${ctx.priorOutputs.securityCompliance?.slice(0, 500) ?? ctx.projectDescription}`,
    domainLine(ctx),
    teamLine(ctx),
    `\nProduce an On-Call Playbook with:`,
    `1. On-Call Responsibilities & Schedule — assign on-call rotation slots to actual team members by name`,
    `2. Incident Severity Levels (P0-P4 with response time SLAs)`,
    `3. Incident Response Process (detect, triage, communicate, resolve, review)`,
    `4. Escalation Matrix — use actual team member names as escalation contacts at each tier`,
    `5. Runbooks for top 10 likely incidents (each: trigger, impact, diagnosis steps, resolution steps, responsible person)`,
    `6. Communication Templates (status page update, customer email, internal Slack) — name the DRI for each from team members above`,
    `7. Post-Incident Review Template — assign facilitator from team members`,
    `8. On-Call Health & Burnout Prevention`,
  ].join('\n'),
};

// ─── Registry ────────────────────────────────────────────────────────────────
export const AGENT_DEFINITIONS: Record<string, AgentDefinition> = {
  manager,
  projectCharter,
  brd,
  stakeholder,
  userStory,
  businessRules,
  feasibility,
  dataModel,
  architecture,
  apiDesign,
  uxResearch,
  interaction,
  uxMockups,
  sprintPlanner,
  taskBreakdown,
  techDebt,
  codeStructure,
  codeSnippets,
  uiComponentLibrary,
  testPlan,
  testCases,
  securityCompliance,
  devopsEngineer,
  infraEngineer,
  observabilityEngineer,
  onCallEngineer,
};
