import type { DomainDefinition, DomainId } from '@/types/domain.types';

export const DOMAINS: Record<DomainId, DomainDefinition> = {
  fintech: {
    id: 'fintech',
    label: 'FinTech',
    color: '#1d4ed8',
    bgColor: '#dbeafe',
    context: `Domain: Financial Technology. Key concerns: PCI-DSS compliance, AML/KYC requirements,
real-time payment processing, fraud detection, regulatory reporting (SOX, GDPR),
high availability (99.99%), audit trails, data encryption at rest and in transit,
open banking APIs (PSD2), core banking integration, risk management frameworks.`,
  },
  healthcare: {
    id: 'healthcare',
    label: 'Healthcare',
    color: '#047857',
    bgColor: '#d1fae5',
    context: `Domain: Healthcare Technology. Key concerns: HIPAA compliance, HL7/FHIR standards,
EHR/EMR integration, PHI data handling, clinical workflows, FDA regulations for medical devices,
patient safety, interoperability between care systems, audit logging, role-based access for
clinicians, telemedicine features, billing (ICD-10, CPT codes).`,
  },
  ecommerce: {
    id: 'ecommerce',
    label: 'E-Commerce',
    color: '#b45309',
    bgColor: '#fef3c7',
    context: `Domain: E-Commerce. Key concerns: high traffic scalability, cart abandonment flows,
payment gateway integration (Stripe, PayPal), inventory management, order fulfillment pipelines,
product catalog search (Elasticsearch), recommendation engines, A/B testing, SEO,
multi-currency/multi-region, GDPR cookie consent, returns & refunds workflows.`,
  },
  saas: {
    id: 'saas',
    label: 'SaaS',
    color: '#6d28d9',
    bgColor: '#ede9fe',
    context: `Domain: Software as a Service. Key concerns: multi-tenancy, subscription billing
(Stripe Billing, usage-based pricing), tenant isolation, feature flags per tier, onboarding flows,
SSO/SAML integration, self-service admin portals, usage analytics, churn prediction,
99.9% SLA, zero-downtime deployments, API rate limiting per tenant.`,
  },
  edtech: {
    id: 'edtech',
    label: 'EdTech',
    color: '#0e7490',
    bgColor: '#cffafe',
    context: `Domain: Education Technology. Key concerns: FERPA compliance (student data privacy),
LMS integration (Canvas, Moodle, Blackboard), SCORM/xAPI content standards, adaptive learning
algorithms, accessibility (WCAG 2.1 AA), gamification, progress tracking, cohort-based
collaboration, video streaming, assignment submission workflows, plagiarism detection APIs.`,
  },
  insurtech: {
    id: 'insurtech',
    label: 'InsurTech',
    color: '#9f1239',
    bgColor: '#ffe4e6',
    context: `Domain: Insurance Technology. Key concerns: actuarial data modeling, policy lifecycle
management (quote-bind-issue), claims processing automation, underwriting rules engines,
regulatory compliance (state insurance laws), reinsurance data exchange, fraud detection,
document OCR for claims, integration with legacy policy admin systems, ACORD standards.`,
  },
  legaltech: {
    id: 'legaltech',
    label: 'LegalTech',
    color: '#374151',
    bgColor: '#f3f4f6',
    context: `Domain: Legal Technology. Key concerns: attorney-client privilege, e-discovery workflows,
contract lifecycle management, e-signature integration (DocuSign), matter management,
conflict-of-interest checking, billing (LEDES format), court filing integrations,
document version control with audit trails, ABA ethical rules compliance, data residency.`,
  },
  retail: {
    id: 'retail',
    label: 'Retail',
    color: '#c2410c',
    bgColor: '#ffedd5',
    context: `Domain: Retail. Key concerns: omnichannel inventory sync (online + in-store),
POS system integration, loyalty program management, demand forecasting, supply chain visibility,
last-mile delivery tracking, shrinkage prevention, seasonal scaling, price optimization,
customer 360 profiles, in-store mobile app features, BOPIS (buy online pick up in store).`,
  },
  manufacturing: {
    id: 'manufacturing',
    label: 'Manufacturing',
    color: '#1e3a5f',
    bgColor: '#e0f0ff',
    context: `Domain: Manufacturing / Industry 4.0. Key concerns: IoT sensor data ingestion,
predictive maintenance, MES/ERP integration (SAP), OEE tracking, quality management (ISO 9001),
production scheduling, supply chain traceability, digital twin modeling,
SCADA integration, safety compliance (OSHA), cold-chain monitoring, batch record management.`,
  },
  govtech: {
    id: 'govtech',
    label: 'GovTech',
    color: '#1e40af',
    bgColor: '#e0e7ff',
    context: `Domain: Government Technology. Key concerns: FedRAMP / StateRAMP authorization,
Section 508 accessibility, FIPS 140-2 cryptography, ATO (Authority to Operate) process,
citizen-facing portal UX, identity proofing (NIST 800-63), open data mandates,
legacy mainframe modernization, procurement compliance (FAR/DFARS), multi-agency data sharing,
disaster recovery (RPO/RTO requirements), FISMA compliance.`,
  },
};
